### ISSUE TITLE
Create a `login` command

### ISSUE THREAD

**Issue by dhilipsiva** [appknox/appknox-python#1]
Create a login command which gets user's credentials, authorises with Appknox and stores the token in `appknox.json` file in home directory.

**Comment by dhilipsiva** [comment]
@subho007 What do you think? Mech secure than Username Password

**Comment by subho007** [comment]
@dhilipsiva I think that should be awesome !

**Comment by subho007** [comment]
was this done @dhilipsiva ?

**Comment by dhilipsiva** [comment]
No Subho. I thought I will create this as when required.

**Comment by subho007** [comment]
@dhilipsiva didn't you hzve a `def login()` already ?

**Comment by dhilipsiva** [comment]
Yeah - but that is different. Its in the library - not the CLI tool.

**Comment by subho007** [comment]
ok, got it, let me implement it then :+1:

**Comment by dhilipsiva** [comment]
Oooh. Okies. :+1:

**Comment by subho007** [comment]
@dhilipsiva I thought and thought over it a loooong time, but then I think we should proceed forward with this only when we have a basic-auth API set-up done. What do you think ?

**Comment by dhilipsiva** [comment]
Yeah subho, Agred. I am putting this on hold because of Epic Upgrade.
